name: eeg
channels:
  - conda-forge
dependencies:
  # Core
  - python=3.11
  - numpy>=1.24
  - scipy>=1.11
  - scikit-learn>=1.3
  - matplotlib>=3.7
  - seaborn>=0.12

  # MNE (core, without extra GUIs)
  - mne-base>=1.5

  # 3D visualization stack (for brain plots and PNG export)
  - pyqt
  - pyvista
  - pyvistaqt
  - vtk

  # Testing
  - pytest>=8

  # Optional: keep pip available if you later need pip-only packages
  - pip